state_dims = {
        "pos": 2,
        "vel": 2,
        "acc": 2,
        "hed": 1,
        "dir": 2,
        "vpref": 2,
        "speed": 1,
        "diff": 2,
        "dist": 1,
        "action": 2,
        "max_action": 1, 
        "goal": 2,
        "state":7,
        "spatial_mask": 1,
        "dt": 1,
    }
